### ISSUE TITLE
Ubuntu problem

### ISSUE THREAD

**Issue by tedthetrumpet** [mjcella/facet#21]
Not an issue exactly, but had a go at installing on UbuntuStudio. Got as far as this, then lots of error messages about 'refused connections', truncated below:
```

jsimon@jsair:~/Documents/GitHub/facet$ npm run facet

> facet@0.4.2 facet
> node js/facet_server.js & node js/transport.js

(node:24037) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1123
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:16)

```
Any ideas? (Sorry, pretty much a linux newbie here!)

**Comment by nnirror** [comment]
First thing to try is commenting out these two lines in js/facet_server.js, and then re-running the "npm run facet" command:

https://github.com/mjcella/facet/blob/main/js/facet_server.js#L142-L143

Let me know if you're still having issues!

**Comment by tedthetrumpet** [comment]
Yes, that seems to have done the trick, I am getting a basic test sine wave now. Thanks.

**Comment by nnirror** [comment]
Great! I just pushed this commit which should fix the issue for non-Mac users:

https://github.com/mjcella/facet/commit/f0edefb306c02eecbbfcebdaa48728bb45805d4a

These two lines run a process every 500ms to get the CPUUsage of the facet server, so it can be displayed in the UI. In the future I want to extend this so it works on all platforms.. right now it just works for Mac since that's the only computer I have.
