### ISSUE TITLE
Example throws error

### ISSUE THREAD

**Issue by tedthetrumpet** [mjcella/facet#22]
```
$('example').iter(16,()=>{this.append(_.randsamp().speed(0.1))}).play();
// error 'TypeError: cannot read property 'speed' of undefined'
```

**Comment by nnirror** [comment]
This should be fixed as of v0.5.5.1. Here's the commit that fixed it:

https://github.com/mjcella/facet/commit/6b4ee9c5f9c5c25e00808a9eeb40d9c118e16404

The issue was that if the function randsamp() didn't return a sample the first time, the randsamp() function would not return anything, so .speed() would run on undefined.

I've wrapped it in a try/catch that tries 32 times before throwing an error about no valid files in the directory 😄
