### ISSUE TITLE
ctrl-c conflicts with copy

### ISSUE THREAD

**Issue by tedthetrumpet** [mjcella/facet#23]
ctrl-c conflicts with copy! eg to copy code elsewhere to work on later?

**Comment by nnirror** [comment]
This is a good question, and it's definitely a blind spot of mine since I developed Facet almost entirely on my Macbook Pro, where the command to clear hooks is [ctrl]+c whereas the command to copy code would be [command]+c. Sounds like  Windows machines (and perhaps other OS-es as well) don't have a [command] modifier, so I think this does need to be changed. 

What modifiers / key combinations do you think would be best for this?

**Comment by tedthetrumpet** [comment]
I'm on ubuntu: and the keyboard shortcut problem looks like it might be tricky. It turns out there is also a problem with ctrl-m, which mutes the tab! So, to unmute facet I have to do ctrl-m again.

I did a bit of searching, and I can't find a simple list of probably-unused shortcuts for web-based apps. On my experiments here, though, it looks like ctrl-period and ctrl-comma might be ok?

**Comment by tedthetrumpet** [comment]
Ok, I found those keycodes in `index.html` and hacked them to be comma and period, seems to work.

**Comment by nnirror** [comment]
Fixed in v0.5.10 👍  thanks for the suggestion of [ctrl + ,] and [ctrl + .], those are the default now.

https://github.com/mjcella/facet/commit/11114c68d460441d5606ec892773e7ccd869e6e7
