### ISSUE TITLE
Samples from subdirectory?

### ISSUE THREAD

**Issue by tedthetrumpet** [mjcella/facet#24]
I have subdirectory of samples called fhitz02. Why does this not work:

`$('dir').randsamp('../samples/fhitz02/').play();`

**Comment by nnirror** [comment]
First, make sure you're starting up Facet via `npm run facet` from the root of the Facet repo directory. In that case, the below command should work (I removed a single dot from the path you pasted). Since the path is relative to where the server is running, i.e. the root Facet repo directory, it needs to reference `./samples` and not `../samples/`  :

`$('dir').randsamp('./samples/fhitz02/').play();`

(This has confused me many times 😄  )
