### ISSUE TITLE
Requirement for Max? Standalone? Linux?

### ISSUE THREAD

**Issue by tedthetrumpet** [mjcella/facet#52]
Is it possible to do audio on mac os using the free Max standalone, or do you need the full paid programme? Also, presumably audio on Linux is not possible, no Max. Any scope for a different audio solution that does not require Max? Pd?

**Comment by nnirror** [comment]
@tedthetrumpet  Great questions...

Regarding Max standalone: I am not sure if the current abstraction would work since it expects you to add it to Max patcher and hook it up to a DAC object, etc. But I think it could be possible to build a Max standalone for at least 2 channel output. Not sure about 4.

I had tried to build a PD equivalent, but I've barely used PD before so I hit some roadblocks - couldn't figure out how to easily parse the UDP data from Facet in PD - and stopped. But it should be possible to build a PD equivalent. I wonder if it would be a good project for someone with PD experience, if you know anyone who might be interested? I could also reach out to some friends.

I will keep this issue open for both these things.

**Comment by nnirror** [comment]
Stereo audio functionality in the browser was added in v1.1.0, so I'm going to close this issue.

https://github.com/mjcella/facet/commit/2fe880638ea59635f79f94e2a19c62b8a9817c47

It should be possible to build audio output capability directly in SuperCollider or PD, but those can maybe be separate issues at some point.
